"""The dev stub must speak the frozen contract (Plan 03 OpenAPI, generated by app.main).

Drives a full Fair flow through the stub and validates every response body against the
OpenAPI response schema for that path, method and status: required keys (optional fields are
present and null), types, enums, nested objects, uuid / date-time formats, and the
`server_time` format. Errors (including a real 429 from the limiter) must match ErrorResponse.
"""

from __future__ import annotations

import os
import re
import uuid
from collections.abc import AsyncIterator
from http.cookiejar import DefaultCookiePolicy
from typing import Any

import httpx
import pytest
from redis.asyncio import Redis

from app.abuse.config import AbuseConfig

os.environ["SIM_MODE"] = "true"

import app.abuse.devstub.app as stub  # noqa: E402
from app.main import create_app  # noqa: E402

# The contract as the code generates it (docs/contract/openapi.json is exported from this,
# with SIM_MODE=true, and `fd openapi --check` keeps the two identical).
SPEC: dict[str, Any] = create_app().openapi()
SCHEMAS: dict[str, Any] = SPEC["components"]["schemas"]
UUID_RE = re.compile(r"^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$")
TIME_RE = re.compile(r"^\d{4}-\d\d-\d\dT\d\d:\d\d:\d\d\.\d{3}Z$")
ADMIN = {"X-Admin-Key": stub.ADMIN_KEY}


def check(value: Any, schema: dict[str, Any], path: str = "$") -> list[str]:
    """Return a list of violations (empty = valid) for the subset of JSON Schema in use."""
    if "$ref" in schema:
        return check(value, SCHEMAS[schema["$ref"].rsplit("/", 1)[1]], path)
    if "anyOf" in schema:
        options = [check(value, s, path) for s in schema["anyOf"]]
        return [] if any(not o for o in options) else [f"{path}: matches no anyOf branch"]
    errs: list[str] = []
    if "enum" in schema and value not in schema["enum"]:
        errs.append(f"{path}: {value!r} not in enum")
    t = schema.get("type")
    kinds = {"string": str, "boolean": bool, "array": list, "object": dict}
    if t == "null" and value is not None:
        errs.append(f"{path}: expected null")
    elif t == "integer" and (not isinstance(value, int) or isinstance(value, bool)):
        errs.append(f"{path}: expected integer, got {value!r}")
    elif t == "number" and (not isinstance(value, int | float) or isinstance(value, bool)):
        errs.append(f"{path}: expected number, got {value!r}")
    elif t in kinds and not isinstance(value, kinds[t]):
        errs.append(f"{path}: expected {t}, got {type(value).__name__}")
    if errs:
        return errs
    fmt = schema.get("format")
    if fmt == "uuid" and not UUID_RE.match(str(value)):
        errs.append(f"{path}: not a uuid: {value!r}")
    if fmt == "date-time" and not TIME_RE.match(str(value)):
        errs.append(f"{path}: not contract date-time: {value!r}")
    if isinstance(value, dict):
        for key in schema.get("required", []):
            if key not in value:
                errs.append(f"{path}: missing required {key!r}")
        for key, sub in schema.get("properties", {}).items():
            if key in value:
                errs += check(value[key], sub, f"{path}.{key}")
        extra = schema.get("additionalProperties")
        if isinstance(extra, dict):
            for key, v in value.items():
                if key not in schema.get("properties", {}):
                    errs += check(v, extra, f"{path}.{key}")
    if isinstance(value, list) and "items" in schema:
        for i, item in enumerate(value):
            errs += check(item, schema["items"], f"{path}[{i}]")
    return errs


def response_schema(method: str, template: str, status: int) -> dict[str, Any]:
    op = SPEC["paths"][template][method.lower()]
    resp = op["responses"].get(str(status)) or op["responses"].get("default")
    assert resp is not None, f"{method} {template} has no {status} response in the contract"
    content = resp.get("content", {}).get("application/json")
    assert content is not None, f"{method} {template} {status} has no JSON body in the contract"
    schema: dict[str, Any] = content["schema"]
    return schema


def conform(r: httpx.Response, method: str, template: str) -> dict[str, Any]:
    body: dict[str, Any] = r.json()
    schema = (
        response_schema(method, template, r.status_code)
        if r.status_code < 400
        else {"$ref": "#/components/schemas/ErrorResponse"}
    )
    errs = check(body, schema)
    assert not errs, f"{method} {template} {r.status_code}: {errs}"
    assert TIME_RE.match(body["server_time"]), body["server_time"]
    return body


@pytest.fixture
async def client(redis: Redis) -> AsyncIterator[httpx.AsyncClient]:
    stub.S = stub.Store()
    stub.REDIS = redis
    stub.LIMITER.redis = redis
    stub.CONFIG.redis = redis
    stub.CONFIG._cfg = AbuseConfig()
    async with httpx.AsyncClient(
        transport=httpx.ASGITransport(app=stub.app), base_url="http://t"
    ) as c:
        c.cookies.jar.set_policy(DefaultCookiePolicy(allowed_domains=[]))
        yield c


async def test_full_fair_flow_matches_the_frozen_contract(client: httpx.AsyncClient) -> None:
    D = "/api/drops/{drop_id}"
    conform(await client.get("/api/healthz"), "GET", "/api/healthz")
    conform(
        await client.put(
            "/api/admin/abuse/config",
            headers=ADMIN,
            json={"layers": {"L7": True}, "thresholds": {"step_up_score": 1}},
        ),
        "PUT",
        "/api/admin/abuse/config",
    )
    created = conform(
        await client.post(
            "/api/admin/drops",
            headers=ADMIN,
            json={"name": "c", "capacity": 2, "mode": "fair", "window_s": 60, "claim_window_s": 60},
        ),
        "POST",
        "/api/admin/drops",
    )
    drop = created["drop_id"]
    conform(await client.get(f"/api/drops/{drop}"), "GET", D)
    conform(
        await client.post(f"/api/admin/drops/{drop}/phase", headers=ADMIN, json={"action": "open"}),
        "POST",
        "/api/admin/drops/{drop_id}/phase",
    )
    tokens = []
    for i in range(3):
        h = {"X-Sim-Client-IP": f"30.1.{i}.1"}
        req = conform(
            await client.post(
                "/api/auth/otp/request",
                headers=h,
                json={"phone": f"+91{8_123_400_000 + i * 7919}", "device_id": f"d{i}"},
            ),
            "POST",
            "/api/auth/otp/request",
        )
        ver = conform(
            await client.post(
                "/api/auth/otp/verify",
                headers=h,
                json={"request_id": req["request_id"], "otp": req["dev_otp"], "device_id": f"d{i}"},
            ),
            "POST",
            "/api/auth/otp/verify",
        )
        h["Authorization"] = f"Bearer {ver['session_token']}"
        tokens.append(h)
        conform(await client.get(f"/api/drops/{drop}/me", headers=h), "GET", D + "/me")
        r = await client.post(f"/api/drops/{drop}/entries", headers=h)
        assert r.status_code == 201
        conform(r, "POST", D + "/entries")
        again = await client.post(f"/api/drops/{drop}/entries", headers=h)
        assert again.status_code == 200
        conform(again, "POST", D + "/entries")
    for action in ("close", "draw"):
        conform(
            await client.post(
                f"/api/admin/drops/{drop}/phase", headers=ADMIN, json={"action": action}
            ),
            "POST",
            "/api/admin/drops/{drop_id}/phase",
        )
    conform(await client.get(f"/api/drops/{drop}"), "GET", D)
    claimed = 0
    for h in tokens:
        me = conform(await client.get(f"/api/drops/{drop}/me", headers=h), "GET", D + "/me")
        entry = me["entry"]
        if entry["status"] == "STEP_UP_REQUIRED":
            conform(
                await client.post(
                    f"/api/drops/{drop}/step-up",
                    headers={**h, "Idempotency-Key": str(uuid.uuid4())},
                    json={"otp": entry["dev_otp"]},
                ),
                "POST",
                D + "/step-up",
            )
            me = conform(await client.get(f"/api/drops/{drop}/me", headers=h), "GET", D + "/me")
            entry = me["entry"]
        if entry["admission_token"]:
            conform(
                await client.post(
                    f"/api/drops/{drop}/claim",
                    headers={**h, "Idempotency-Key": str(uuid.uuid4())},
                    json={"admission_token": entry["admission_token"]},
                ),
                "POST",
                D + "/claim",
            )
            claimed += 1
            me = conform(await client.get(f"/api/drops/{drop}/me", headers=h), "GET", D + "/me")
            assert me["allocation"] is not None
    assert claimed == 2
    for p in ("integrity", "metrics", "draw-proof"):
        conform(
            await client.get(f"/api/admin/drops/{drop}/{p}", headers=ADMIN),
            "GET",
            "/api/admin/drops/{drop_id}/" + p,
        )
    conform(
        await client.post(
            "/api/sim/telemetry",
            headers={"X-Sim-Key": stub.SIM_KEY},
            json={"run_id": "r", "attack_phase": "flood"},
        ),
        "POST",
        "/api/sim/telemetry",
    )


async def test_errors_and_rate_limits_use_the_contract_envelope(client: httpx.AsyncClient) -> None:
    conform(await client.get("/api/drops/00000000-0000-0000-0000-000000000000/me"), "GET", "")
    rejected = None
    for _ in range(80):  # anonymous flood from one IP: the limiter answers 429
        r = await client.get(
            "/api/drops/00000000-0000-0000-0000-000000000000",
            headers={"X-Sim-Client-IP": "6.6.6.6"},
        )
        if r.status_code == 429:
            rejected = r
            break
    assert rejected is not None
    body = conform(rejected, "GET", "")
    assert body["error"]["code"] == "RATE_LIMITED"
    assert int(rejected.headers["retry-after"]) * 1000 >= body["error"]["retry_after_ms"]


async def test_config_endpoint_accepts_only_the_contract_shape(client: httpx.AsyncClient) -> None:
    bad = [
        {"thresholds": {"step_up_score": 50}},  # layers is required
        {"layers": {"L1": True}, "limits": {"L2": {"ip_anon": [1, 1]}}},  # not in the contract
        {"layers": {"L1": True}, "thresholds": {"otp_per_ip_count": [1, 2]}},  # numbers only
        {"layers": {"L9": True}},
    ]
    for body in bad:
        r = await client.put("/api/admin/abuse/config", headers=ADMIN, json=body)
        assert r.status_code == 400, body
        assert conform(r, "PUT", "")["error"]["code"] == "VALIDATION_ERROR"
