-- migrate:up

-- create_drop: the only way a drop and its seats come into existence. One function call is one
-- transaction, so a drop can never exist without its `capacity` seats (Plan 02 section 4.4).
-- SECURITY DEFINER because the application role has no INSERT right on drops or seats
-- (20261004100300): it can create drops only through this function. search_path is pinned so a
-- caller cannot shadow pg_catalog or public objects.
CREATE FUNCTION create_drop(
    p_name           text,
    p_capacity       int,
    p_mode           text,
    p_window_s       int,
    p_claim_window_s int,
    p_seed_commit    text,
    p_seed           text        DEFAULT NULL,
    p_reg_opens_at   timestamptz DEFAULT NULL,
    p_reg_closes_at  timestamptz DEFAULT NULL
) RETURNS uuid
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
DECLARE
    v_drop_id uuid;
BEGIN
    INSERT INTO drops (name, capacity, mode, phase, window_s, claim_window_s,
                       seed_commit, seed, reg_opens_at, reg_closes_at)
    VALUES (p_name, p_capacity, p_mode, 'SCHEDULED', p_window_s, p_claim_window_s,
            p_seed_commit, p_seed, p_reg_opens_at, p_reg_closes_at)
    RETURNING id INTO v_drop_id;

    INSERT INTO seats (drop_id, capacity, seat_no, status)
    SELECT v_drop_id, p_capacity, n, 'free'
    FROM generate_series(1, p_capacity) AS n;

    RETURN v_drop_id;
END;
$$;

-- Allocations are an append-only ledger. UPDATE is never allowed. DELETE and TRUNCATE are allowed
-- only inside admin_reset_drop (below), which sets a transaction-local flag. The flag is checked
-- together with the caller's identity: the application role is refused even if it sets the flag.
-- This trigger guards against bugs and against a superuser's slip; the real access control is the
-- grants in 20261004100300 (the application role has no UPDATE/DELETE/TRUNCATE on allocations).
CREATE FUNCTION allocations_append_only() RETURNS trigger
LANGUAGE plpgsql
SET search_path = pg_catalog, public
AS $$
BEGIN
    IF TG_OP = 'DELETE'
       AND coalesce(current_setting('fairdrop.resetting', true), '') = 'on'
       AND current_user <> 'fairdrop_app' THEN
        RETURN OLD;
    END IF;
    RAISE EXCEPTION 'allocations is append-only (% refused)', TG_OP
        USING ERRCODE = 'integrity_constraint_violation';
END;
$$;

CREATE TRIGGER allocations_no_update_delete
    BEFORE UPDATE OR DELETE ON allocations
    FOR EACH ROW EXECUTE FUNCTION allocations_append_only();

CREATE FUNCTION allocations_no_truncate() RETURNS trigger
LANGUAGE plpgsql
SET search_path = pg_catalog, public
AS $$
BEGIN
    IF coalesce(current_setting('fairdrop.resetting', true), '') = 'on'
       AND current_user <> 'fairdrop_app' THEN
        RETURN NULL;
    END IF;
    RAISE EXCEPTION 'allocations is append-only (TRUNCATE refused)'
        USING ERRCODE = 'integrity_constraint_violation';
END;
$$;

CREATE TRIGGER allocations_no_truncate
    BEFORE TRUNCATE ON allocations
    FOR EACH STATEMENT EXECUTE FUNCTION allocations_no_truncate();

-- admin_reset_drop: wipe one drop's run data and start the next run (Plan 06). Returns the new
-- run_no. Order matters: allocations first (they point at seats), then seats, then entries.
-- Users, sessions and drop_runs are kept. The seed is regenerated by the application afterwards.
CREATE FUNCTION admin_reset_drop(p_drop_id uuid) RETURNS int
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
DECLARE
    v_run_no int;
BEGIN
    PERFORM 1 FROM drops WHERE id = p_drop_id FOR UPDATE;
    IF NOT FOUND THEN
        RAISE EXCEPTION 'drop % not found', p_drop_id USING ERRCODE = 'no_data_found';
    END IF;

    PERFORM set_config('fairdrop.resetting', 'on', true);  -- true = local to this transaction
    DELETE FROM allocations WHERE drop_id = p_drop_id;
    PERFORM set_config('fairdrop.resetting', 'off', true);

    UPDATE seats SET status = 'free', entry_id = NULL, sold_at = NULL
    WHERE drop_id = p_drop_id AND status <> 'free';
    DELETE FROM entries WHERE drop_id = p_drop_id;
    DELETE FROM idempotency_records WHERE drop_id = p_drop_id;

    UPDATE drops
    SET run_no = run_no + 1, drawn_at = NULL, closed_at = NULL, done_at = NULL, entry_set_hash = NULL
    WHERE id = p_drop_id
    RETURNING run_no INTO v_run_no;

    RETURN v_run_no;
END;
$$;

-- Nobody but the roles we grant may call the SECURITY DEFINER functions.
REVOKE ALL ON FUNCTION create_drop(text, int, text, int, int, text, text, timestamptz, timestamptz) FROM PUBLIC;
REVOKE ALL ON FUNCTION admin_reset_drop(uuid) FROM PUBLIC;

-- migrate:down

-- Forward-only (see 20261004100000_core_schema.sql).
