"""Pattern tests for the Rule R1 guard (pure functions, no git needed)."""

from __future__ import annotations

import unittest

from fd.attribution import _push_rev_args, scan_identity, scan_message

# Built from parts so this file itself never contains a forbidden literal on one line.
ROBOT = "\U0001f916"


class RejectedMessages(unittest.TestCase):
    def assertRejected(self, text: str) -> None:
        self.assertTrue(scan_message(text), f"expected rejection: {text!r}")

    def test_co_authored_by_claude(self) -> None:
        self.assertRejected("feat: x\n\nCo-Authored-By: Claude Sonnet <noreply@anthropic.com>")

    def test_trailer_variants(self) -> None:
        for key in ("Co-developed-by", "Assisted-by", "Reviewed-by", "Signed-off-by"):
            self.assertRejected(f"feat: x\n\n{key}: Claude <c@example.com>")
            self.assertRejected(f"feat: x\n\n{key.lower()}: someone@anthropic.example")

    def test_noreply_address_anywhere(self) -> None:
        self.assertRejected("fix: thanks noreply@anthropic.com for nothing")

    def test_generated_with_line(self) -> None:
        self.assertRejected("feat: x\n\nGenerated with [Claude Code](https://x)")
        self.assertRejected("feat: x\n\ngenerated by claude")

    def test_claude_code_urls(self) -> None:
        self.assertRejected("see https://claude.com/claude-code")
        self.assertRejected("see https://claude.ai/code/session_123")

    def test_robot_emoji(self) -> None:
        self.assertRejected(f"feat: x {ROBOT}")

    def test_case_insensitive(self) -> None:
        self.assertRejected("CO-AUTHORED-BY: CLAUDE <X@Y.Z>")


class AllowedMessages(unittest.TestCase):
    def test_talking_about_the_tools_is_fine(self) -> None:
        for text in (
            "chore: disable Claude Code attribution in project settings",
            "docs: explain why Anthropic trailers are rejected",
            "feat(fd): add attribution-check",
            "Co-Authored-By: Ameya Deore <deoreameya@gmail.com>",
            "Reviewed-by: Akshay <akshay@example.com>",
        ):
            self.assertEqual(scan_message(text), [], text)


class Identities(unittest.TestCase):
    def test_ai_names_and_emails_are_rejected(self) -> None:
        self.assertTrue(scan_identity("Claude", "me@example.com", "author"))
        self.assertTrue(scan_identity("Dev", "noreply@anthropic.com", "committer"))
        self.assertTrue(scan_identity("Claude Code", "x@y.z", "author"))

    def test_owner_identity_is_fine(self) -> None:
        self.assertEqual(scan_identity("Ameya Deore", "deoreameya@gmail.com", "author"), [])


class PushStdin(unittest.TestCase):
    def test_deleting_a_ref_scans_nothing(self) -> None:
        line = f"(delete) {'0' * 40} refs/heads/x {'a' * 40}"
        self.assertEqual(_push_rev_args(line), [])

    def test_garbage_lines_are_ignored(self) -> None:
        self.assertEqual(_push_rev_args("not four fields\n\n"), [])


if __name__ == "__main__":
    unittest.main()
