"""`fd secrets`: write .env from .env.example with random secrets and LF endings."""

from __future__ import annotations

import secrets

from fd import console, envfile, repo


def generate(*, force: bool) -> int:
    root = repo.repo_root()
    example = root / ".env.example"
    target = root / ".env"
    if not example.is_file():
        console.fail(".env.example not found")
        return 1
    if target.exists() and not force:
        console.fail(".env already exists; refusing to overwrite (use --force to replace it)")
        return 1

    entries = envfile.parse_example(example.read_text(encoding="utf-8"))
    values = {
        e.key: (secrets.token_hex(32) if e.secret and not e.value else e.value) for e in entries
    }
    values = envfile.expand_refs(values)

    lines = [
        "# Generated by `uv run fd secrets` from .env.example. Never commit this file.",
        *(f"{key}={value}" for key, value in values.items()),
    ]
    # newline="\n": a CR inside .env ends up inside every secret via compose env_file.
    with target.open("w", encoding="utf-8", newline="\n") as handle:
        handle.write("\n".join(lines) + "\n")

    generated = sum(1 for e in entries if e.secret and not e.value)
    console.ok(f"wrote .env ({len(values)} variables, {generated} random secrets, LF endings)")
    return 0
